backend/controllers/report-controller.ts, backend/express.ts, backend/routes/data-router.ts, backend/routes/index.ts
I added some backend code for the add reports routing
=> added routing for add reports page

.github/ISSUE_TEMPLATE/task.md
This does nothing to the code. It adds a folder for GitHub issue templates.
=> Add template folder

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/spike.md, .github/ISSUE_TEMPLATE/user-story.md
Templates for Capstone Students
=> Update issue templates

frontend/src/components/Categories/Categories.tsx, frontend/src/components/Soil-Coverage-Compare.tsx, frontend/src/main.tsx
=> Create coverage compare

frontend/src/App.tsx, frontend/src/components/Categories/Categories.tsx, frontend/src/components/DummyFiles/Soil-Coverage-Capture.tsx, frontend/src/components/DummyFiles/Soil-Coverage-Compare.tsx, frontend/src/components/Home.tsx
=> Added routing for capture & compare for soil coverage

frontend/src/App.tsx, frontend/src/components/DummyFiles/Soil-Coverage-Compare.tsx
=> Routed to correct soil coverage compare web page

frontend/src/components/Soil-Coverage-Compare.tsx
=> Flexbox added to buttons for aligning

frontend/src/components/Soil-Coverage-Compare.tsx
=> Added handleClick functionality to nav buttons

frontend/src/components/DummyFiles/Soil-Coverage-Capture.tsx, frontend/src/components/common/Header/header.styles.ts
=> Added new media queries to fix styling issues with the header image, header size and text font.

backend/Dockerfile, backend/controllers/report-controller.ts, backend/package.json, backend/prisma/schema.prisma, docker-compose.yaml
Updated dockerfile and compose so prisma will generate the client and migrate on each docker build
=> Updated docker/prisma

backend/Dockerfile, backend/package.json, docker-compose.yaml
=> fix: Fixed backend hot reloading (watch changes)

backend/controllers/report-controller.ts, backend/express.ts, backend/package-lock.json, backend/package.json, backend/routes/data-router.ts, frontend/src/components/Categories/Categories.tsx, frontend/src/components/Home.tsx, frontend/src/components/Login/Login.tsx, frontend/src/components/Soil-Coverage-Capture.tsx, frontend/src/components/Soil-Coverage-Compare.tsx, frontend/src/components/common/Header/Header.tsx, frontend/src/components/common/Slider/Slider.tsx
=> Hook up login name to backend

frontend/src/components/Soil-Coverage-Compare.tsx, frontend/src/components/common/Carousel/Carousel.tsx, frontend/src/components/common/Tabs/Tabs.tsx, frontend/src/components/common/Tabs/tabs.styles.ts
=> Implemented tab functionality to Compare page. Added skeleton for Carousel - to be done later

frontend/package-lock.json, frontend/src/components/common/UploadButton/UploadButton.tsx
=> Added alert to run with instructions before user adds an image

frontend/src/components/Soil-Coverage-Compare.tsx
=> fixed error

frontend/src/App.css, frontend/src/components/common/Button/button.styles.ts, frontend/src/components/common/Carousel/Carousel.tsx, frontend/src/components/common/InputField/inputField.styles.ts, frontend/src/components/common/LogoutButton/logoutButton.styles.css, frontend/src/components/common/Slider/slider.styles.ts, frontend/src/components/common/UploadButton/UploadButton.tsx, frontend/src/components/common/UploadButton/uploadButton.styles.css
Updated stylings on the capture and compare page by making pictures responsive based on screen height, updating button sizing, and fixing div sizes.
=> Css changes

backend/controllers/report-controller.ts, backend/routes/data-router.ts, frontend/src/App.css, frontend/src/components/Soil-Coverage-Compare.tsx, frontend/src/components/common/Carousel/Carousel.tsx, frontend/src/components/common/Chart/Chart.tsx, frontend/src/components/common/Tabs/tabs.styles.ts
A filter for the soil coverage compare page that filters by a set amount of years. There are a small amount of css changes and one new function in the api controller for this update.
=> added filter to soil coverage compare page

backend/prisma/migrations/20250629231824_added_oma_reports_table/migration.sql, backend/prisma/schema.prisma, frontend/package-lock.json, frontend/package.json
Added a new table to the database for OMA reports. The table is very similar to the cov reports table except it also doesnt save the uploaded image and instead saves the images colour information. It has a createdAt, hue, value, chroma, and optional notes column. I also included a new dependency that will make converting to munsell a lot easier.
=> added oma_report table to database

backend/controllers/report-controller.ts, backend/routes/data-router.ts, frontend/src/components/Organic-Matter-Analysis-Capture.tsx, frontend/src/components/Organic-Matter-Analysis-Compare.tsx, frontend/src/components/Soil-Coverage-Compare.tsx, frontend/src/components/common/Chart/Chart.tsx
=> OMA graph implementation

backend/controllers/report-controller.ts, backend/routes/data-router.ts, frontend/src/components/Organic-Matter-Analysis-Capture.tsx
=> Save capability for OMA

backend/controllers/report-controller.ts, frontend/src/components/Soil-Penetration-Capture.tsx, frontend/src/components/common/Chart/Chart.tsx
Just a small fix to make the addSoilPenetrationReport function work again
=> fixed the small issue from last commit

frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/components/Organic-Matter-Analysis-Capture.tsx, frontend/src/components/common/ColorExtractor/ColorExtractor.tsx, frontend/src/components/common/UploadButton/UploadButton.tsx, frontend/src/components/common/UploadButton/uploadButton.styles.css
Added markers to the uploaded image. Markers use a canvas in a colour extractor component like an eyedropper tool to extract the colours within the part the image was marked. Markers can be removed or reset. Only two markers are allowed on the image, one for paper and one for the soil. Removed Notes input field and button to create notes. 
=> Integrate image interactivity

frontend/src/components/common/Chart/Chart.tsx
=> Implement bar graphs

frontend/src/App.css, frontend/src/components/common/UploadButton/UploadButton.tsx
fixed the modal sizing a little bit to help prevent the logout problem
=> Modal propagation

frontend/src/components/Organic-Matter-Analysis-Capture.tsx, frontend/src/components/common/InformationIcon/InformationIcon.tsx, frontend/src/components/common/UploadButton/UploadButton.tsx
=> Completed removal of penetrameter, and insertion of tabs for OMA

frontend/src/App.css
I changed the footer to a fixed position to try and fix the sizing issue some phones may have.
=> changed position absolute to position fixed

.github/workflows/.deploy.yml, .github/workflows/merge.yml, backend/express.ts, backend/openshift.deploy.yml, frontend/openshift.deploy.yml
---
Thanks for the PR!
Deployments, as required, will be available below:
- [Frontend](https://nr-sustainment-capstone-2025-156-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2025-156-backend.apps.silver.devops.gov.bc.ca/api/health)
Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-sustainment-capstone-2025/actions/workflows/analysis.yml)
After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-sustainment-capstone-2025/act …
=> chore(ci): deploy to test
